require('@testing-library/jest-dom');
const { TextEncoder, TextDecoder } = require('util');
global.TextEncoder = TextEncoder;
global.TextDecoder = TextDecoder;
const { ReadableStream } = require('node:stream/web');
global.ReadableStream = ReadableStream;
const { MessagePort } = require('node:worker_threads');
global.MessagePort = MessagePort;
const { Request, Response, fetch } = require('undici');
global.Request = Request;
global.Response = Response;
global.fetch = fetch;