module.exports = {
  useRouter: () => ({
    push: jest.fn(),
    replace: jest.fn(),
    refresh: jest.fn(),
    back: jest.fn(),
    prefetch: jest.fn(),
    beforePopState: jest.fn(),
    push: jest.fn(),
    replace: jest.fn(),
    refresh: jest.fn(),
    pathname: '/mock-path',
    asPath: '/mock-path?foo=bar',
    query: { foo: 'bar' },
    route: '/mock-path',
    basePath: '',
    locale: 'en',
    isFallback: false,
    events: {
      on: jest.fn(),
      off: jest.fn(),
      emit: jest.fn(),
    },
  }),
};